// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi(in *jlexer.Lexer, out *Thesis) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "author_id":
			out.AuthorID = int(in.Int())
		case "section_id":
			out.SectionID = int(in.Int())
		case "subsection_id":
			out.SubSectionsID = int(in.Int())
		case "originality":
			out.Originality = float64(in.Float64())
		case "subject":
			out.Subject = string(in.String())
		case "thesis":
			out.Thesis = string(in.String())
		case "custom_fields":
			out.Fields = string(in.String())
		case "DateCreate":
			out.DateCreate = string(in.String())
		case "DateLastChange":
			out.DateLastChange = string(in.String())
		case "Status":
			out.Status = string(in.String())
		case "Changes":
			out.Changes = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi(out *jwriter.Writer, in Thesis) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"author_id\":"
		out.RawString(prefix)
		out.Int(int(in.AuthorID))
	}
	{
		const prefix string = ",\"section_id\":"
		out.RawString(prefix)
		out.Int(int(in.SectionID))
	}
	{
		const prefix string = ",\"subsection_id\":"
		out.RawString(prefix)
		out.Int(int(in.SubSectionsID))
	}
	{
		const prefix string = ",\"originality\":"
		out.RawString(prefix)
		out.Float64(float64(in.Originality))
	}
	{
		const prefix string = ",\"subject\":"
		out.RawString(prefix)
		out.String(string(in.Subject))
	}
	{
		const prefix string = ",\"thesis\":"
		out.RawString(prefix)
		out.String(string(in.Thesis))
	}
	{
		const prefix string = ",\"custom_fields\":"
		out.RawString(prefix)
		out.String(string(in.Fields))
	}
	{
		const prefix string = ",\"DateCreate\":"
		out.RawString(prefix)
		out.String(string(in.DateCreate))
	}
	{
		const prefix string = ",\"DateLastChange\":"
		out.RawString(prefix)
		out.String(string(in.DateLastChange))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"Changes\":"
		out.RawString(prefix)
		out.String(string(in.Changes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Thesis) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Thesis) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Thesis) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Thesis) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi(l, v)
}
func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi1(in *jlexer.Lexer, out *GetThesisByFilterResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "thesis":
			(out.Thesis).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi1(out *jwriter.Writer, in GetThesisByFilterResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"thesis\":"
		out.RawString(prefix[1:])
		(in.Thesis).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetThesisByFilterResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetThesisByFilterResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetThesisByFilterResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetThesisByFilterResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi1(l, v)
}
func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi2(in *jlexer.Lexer, out *GetThesisByFilterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi2(out *jwriter.Writer, in GetThesisByFilterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetThesisByFilterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetThesisByFilterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetThesisByFilterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetThesisByFilterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi2(l, v)
}
func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi3(in *jlexer.Lexer, out *CreateThesisResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi3(out *jwriter.Writer, in CreateThesisResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (c CreateThesisResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi3(&w, c)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (c CreateThesisResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi3(w, c)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (c *CreateThesisResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi3(&r, c)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (c *CreateThesisResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi3(l, c)
}
func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi4(in *jlexer.Lexer, out *CreateThesisRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "author_id":
			out.AuthorID = int(in.Int())
		case "section_id":
			out.SectionID = int(in.Int())
		case "subsection_id":
			out.SubSectionsID = int(in.Int())
		case "originality":
			out.Originality = float64(in.Float64())
		case "subject":
			out.Subject = string(in.String())
		case "thesis":
			out.Thesis = string(in.String())
		case "custom_fields":
			out.Fields = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi4(out *jwriter.Writer, in CreateThesisRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"author_id\":"
		out.RawString(prefix)
		out.Int(int(in.AuthorID))
	}
	{
		const prefix string = ",\"section_id\":"
		out.RawString(prefix)
		out.Int(int(in.SectionID))
	}
	{
		const prefix string = ",\"subsection_id\":"
		out.RawString(prefix)
		out.Int(int(in.SubSectionsID))
	}
	{
		const prefix string = ",\"originality\":"
		out.RawString(prefix)
		out.Float64(float64(in.Originality))
	}
	{
		const prefix string = ",\"subject\":"
		out.RawString(prefix)
		out.String(string(in.Subject))
	}
	{
		const prefix string = ",\"thesis\":"
		out.RawString(prefix)
		out.String(string(in.Thesis))
	}
	{
		const prefix string = ",\"custom_fields\":"
		out.RawString(prefix)
		out.String(string(in.Fields))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (c CreateThesisRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi4(&w, c)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (c CreateThesisRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi4(w, c)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (c *CreateThesisRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi4(&r, c)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (c *CreateThesisRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi4(l, c)
}
func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi5(in *jlexer.Lexer, out *ChangeThesisResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi5(out *jwriter.Writer, in ChangeThesisResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeThesisResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeThesisResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeThesisResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeThesisResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi5(l, v)
}
func easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi6(in *jlexer.Lexer, out *ChangeThesisRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "author_id":
			if in.IsNull() {
				in.Skip()
				out.AuthorID = nil
			} else {
				if out.AuthorID == nil {
					out.AuthorID = new(int)
				}
				*out.AuthorID = int(in.Int())
			}
		case "section_id":
			if in.IsNull() {
				in.Skip()
				out.SectionID = nil
			} else {
				if out.SectionID == nil {
					out.SectionID = new(int)
				}
				*out.SectionID = int(in.Int())
			}
		case "subsection_id":
			if in.IsNull() {
				in.Skip()
				out.SubSectionsID = nil
			} else {
				if out.SubSectionsID == nil {
					out.SubSectionsID = new(int)
				}
				*out.SubSectionsID = int(in.Int())
			}
		case "originality":
			if in.IsNull() {
				in.Skip()
				out.Originality = nil
			} else {
				if out.Originality == nil {
					out.Originality = new(float64)
				}
				*out.Originality = float64(in.Float64())
			}
		case "subject":
			if in.IsNull() {
				in.Skip()
				out.Subject = nil
			} else {
				if out.Subject == nil {
					out.Subject = new(string)
				}
				*out.Subject = string(in.String())
			}
		case "thesis":
			if in.IsNull() {
				in.Skip()
				out.Thesis = nil
			} else {
				if out.Thesis == nil {
					out.Thesis = new(string)
				}
				*out.Thesis = string(in.String())
			}
		case "custom_fields":
			if in.IsNull() {
				in.Skip()
				out.Fields = nil
			} else {
				if out.Fields == nil {
					out.Fields = new(string)
				}
				*out.Fields = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi6(out *jwriter.Writer, in ChangeThesisRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"author_id\":"
		out.RawString(prefix)
		if in.AuthorID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.AuthorID))
		}
	}
	{
		const prefix string = ",\"section_id\":"
		out.RawString(prefix)
		if in.SectionID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.SectionID))
		}
	}
	{
		const prefix string = ",\"subsection_id\":"
		out.RawString(prefix)
		if in.SubSectionsID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.SubSectionsID))
		}
	}
	{
		const prefix string = ",\"originality\":"
		out.RawString(prefix)
		if in.Originality == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.Originality))
		}
	}
	{
		const prefix string = ",\"subject\":"
		out.RawString(prefix)
		if in.Subject == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Subject))
		}
	}
	{
		const prefix string = ",\"thesis\":"
		out.RawString(prefix)
		if in.Thesis == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Thesis))
		}
	}
	{
		const prefix string = ",\"custom_fields\":"
		out.RawString(prefix)
		if in.Fields == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Fields))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeThesisRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeThesisRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComCodingSquireMaiMonolitPkgApi6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeThesisRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeThesisRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComCodingSquireMaiMonolitPkgApi6(l, v)
}
