package httpserver

import "net/http"

const (
	// URIPrefix ...
	URIPrefix = "/api/v1/segment"

	// URIPathClientCreateSegment ...
	URIPathClientCreateSegment = URIPrefix + "/create"
	// URIPathClientChangeSegment ...
	URIPathClientChangeSegment = URIPrefix + "/change"
	// URIPathClientGetSegmentByFilter ...
	URIPathClientGetSegmentByFilter = URIPrefix + "/get"

	// HTTPMethodCreateSegment ...
	HTTPMethodCreateSegment = http.MethodPost
	// HTTPMethodChangeSegment ...
	HTTPMethodChangeSegment = http.MethodPost
	// HTTPMethodGetSegmentByFilter ...
	HTTPMethodGetSegmentByFilter = http.MethodPost
)
